//! Pure resolution and rendering of the private generated-flake tree.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Component, Path, PathBuf};

use super::error::GeneratedFlakeErrorKind;
use super::input::{InputDeclarer, merge_inputs, parse_inputs};
use super::{
    ArtifactForm, ArtifactKind, GeneratedFlakeError, Manifest, ResolvedArtifact, XdgRoots,
    resolve_artifact,
};
use crate::diagnostic::{Locus, Namespace};

const FLAKE_FILE: &str = "flake.nix";
const MANIFEST_SOURCE_FILE: &str = "manifest.toml";
const MANIFEST_MODULE_FILE: &str = "manifest-leaf.nix";
const LOCK_FILE: &str = "flake.lock";
const OPTIONS_MODULE_FILE: &str = "vivarium-options.nix";
const REPORT_FILE: &str = "vivarium-report.nix";

/// The attribute both config readers evaluate, and the one place its name is spelled.
pub const REPORT_ATTR: &str = "vivariumReport";

/// The tool-owned option surface, carried into every generated tree.
///
/// Embedded rather than referenced: ADR-0058 makes the generated flake self-contained and
/// regenerable, so a path out of it into this repository would make vivarium's own checkout a
/// build input of every sandbox. `nix/default.nix` admits both files into the crate source for
/// this reason.
const OPTIONS_MODULE: &str = include_str!("../../nix/vivarium-options.nix");

/// The report expression both `viv config eval` and `viv config sources` read.
const REPORT_MODULE: &str = include_str!("../../nix/vivarium-report.nix");

/// The embedded product tree, written into every generated tree under this prefix.
///
/// The binary supplies vivarium (ADR-0102): the product Nix tree and the crate source the
/// guest-agent derivation builds from travel inside the tool and are rendered on every
/// preparation, referenced relatively — the same seam the two files above ride. Written as
/// source, so the guest still evaluates against the project's own `nixpkgs` and `microvm`.
/// The list is generated by `build.rs`, which owns what is admitted and what stays out.
const EMBEDDED_TREE_DIRECTORY: &str = "vivarium";

mod embedded {
    include!(concat!(env!("OUT_DIR"), "/embedded_tree.rs"));
}

/// One embedded file by its repository-relative path.
///
/// The seam for cross-language pairings: with no Nix-built host binary left to inspect, a
/// constant shared by the crate and the product Nix tree is asserted against the embedded copy
/// the binary actually ships (see `src/launch/spec.rs`), keeping the rule of two independently
/// realised artifacts.
#[cfg(test)]
#[must_use]
pub fn embedded_file(path: &str) -> Option<&'static [u8]> {
    embedded::EMBEDDED_TREE
        .iter()
        .find(|(name, _)| *name == path)
        .map(|(_, bytes)| *bytes)
}

/// The two inputs every generated flake carries whatever a manifest declares.
///
/// Their default resolves a branch, which is what a released vivarium should do: a user binding a
/// project today gets today's upstream, pinned from then on by the lock the first evaluation
/// creates. That is also a trap for this repository's own lanes, which evaluate from a fresh data
/// root over and over: branch resolution queries the GitHub API every time and is answered `403`
/// after sixty of them, closing the `ConfigEval` gate for a reason that is about GitHub.
///
/// So both are overridable by environment, and every development lane sets them to the store paths
/// this repository's own product flake already pins — no network, no API, and the same revisions
/// vivarium is developed against. Reached through the injected [`Environment`] rather than the
/// process, so the renderer stays a function of its inputs.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BaselineInputs {
    /// The `nixpkgs` flake reference.
    pub nixpkgs: String,
    /// The `microvm` flake reference.
    pub microvm: String,
}

/// The variable a development lane sets to pin `nixpkgs`.
pub const BASELINE_NIXPKGS_VARIABLE: &str = "VIVARIUM_BASELINE_NIXPKGS";

/// The variable a development lane sets to pin `microvm`.
pub const BASELINE_MICROVM_VARIABLE: &str = "VIVARIUM_BASELINE_MICROVM";

impl Default for BaselineInputs {
    fn default() -> Self {
        Self {
            nixpkgs: "github:NixOS/nixpkgs/nixos-unstable".to_owned(),
            microvm: "github:astro/microvm.nix".to_owned(),
        }
    }
}

impl BaselineInputs {
    /// Reads the overrides a development lane sets, falling back to the shipped references.
    #[must_use]
    pub fn from_environment(environment: &impl super::Environment) -> Self {
        let read = |name| {
            environment
                .variable(name)
                .and_then(|value| value.into_string().ok())
                .filter(|value| !value.trim().is_empty())
        };
        let shipped = Self::default();
        Self {
            nixpkgs: read(BASELINE_NIXPKGS_VARIABLE).unwrap_or(shipped.nixpkgs),
            microvm: read(BASELINE_MICROVM_VARIABLE).unwrap_or(shipped.microvm),
        }
    }
}

pub use super::input::FlakeInput;

/// All durable paths involved in preparing one target.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFlakePaths {
    /// The regenerable generated tree.
    pub directory: PathBuf,
    /// The per-target tool-owned pin.
    pub owned_lock: PathBuf,
    /// The optional per-directory-manifest team pin.
    pub override_lock: Option<PathBuf>,
}

/// The one lock selected for this preparation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EffectiveLock {
    /// A read-only team pin beside a directory-form manifest.
    Override { path: PathBuf },
    /// A tool-owned pin already exists and ordinary build must not move it.
    OwnedExisting { path: PathBuf },
    /// No pin exists yet; a successful first build may install exactly one.
    OwnedMissing { path: PathBuf },
}

impl EffectiveLock {
    /// The selected durable lock path, whether or not it exists yet.
    #[must_use]
    pub fn path(&self) -> &Path {
        match self {
            Self::Override { path }
            | Self::OwnedExisting { path }
            | Self::OwnedMissing { path } => path,
        }
    }

    /// Whether a successful build may persist a newly created lock.
    #[must_use]
    pub const fn may_persist_created(&self) -> bool {
        matches!(self, Self::OwnedMissing { .. })
    }
}

/// A validated `extends` target and the one manifest directory it requires.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResolvedExtends {
    pub(super) directory: PathBuf,
    pub(super) relative_target: PathBuf,
    pub(super) manifest_name: String,
}

/// The complete read-only composition closure.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResolvedComposition {
    /// The selected image.
    pub image: ResolvedArtifact,
    /// The selected pieces, preserving declaration order and duplicates.
    pub pieces: Vec<ResolvedArtifact>,
    /// The bounded manifest module, when present.
    pub extends: Option<ResolvedExtends>,
    /// Artifact-declared inputs sorted by name.
    pub inputs: BTreeMap<String, FlakeInput>,
    /// Paths for generated and durable artifacts.
    pub paths: GeneratedFlakePaths,
    /// The one effective lock decision.
    pub effective_lock: EffectiveLock,
}

/// One operation in the deterministic generated-tree plan.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum GeneratedEntry {
    /// Bytes rendered by vivarium.
    RenderedFile {
        destination: PathBuf,
        bytes: Vec<u8>,
    },
    /// One source file copied byte-for-byte.
    CopiedFile {
        source: PathBuf,
        destination: PathBuf,
    },
    /// A complete source directory copied without following symlinks.
    CopiedTree {
        source: PathBuf,
        destination: PathBuf,
    },
}

impl GeneratedEntry {
    pub(super) fn destination(&self) -> &Path {
        match self {
            Self::RenderedFile { destination, .. }
            | Self::CopiedFile { destination, .. }
            | Self::CopiedTree { destination, .. } => destination,
        }
    }
}

/// The complete, inspectable shape to publish.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFlakePlan {
    /// Final generated directory.
    pub directory: PathBuf,
    /// Ordered operations beneath that directory.
    pub entries: Vec<GeneratedEntry>,
    /// The lock decision carried into publication and later persistence.
    pub effective_lock: EffectiveLock,
    /// The owned lock's migrated bytes when it carried a dead `vivarium` node (ADR-0102).
    ///
    /// The staged tree already gets these bytes through its `flake.lock` entry; this copy is for
    /// publication to also rewrite the durable owned lock, so the shed happens once rather than
    /// on every preparation forever.
    pub migrated_lock: Option<Vec<u8>>,
}

/// A fully published generated flake, which `evaluate.rs` runs Nix against.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PreparedFlake {
    /// The published flake directory.
    pub directory: PathBuf,
    /// The lock selected before publication.
    pub effective_lock: EffectiveLock,
    /// Whether this preparation shed a dead `vivarium` node from the owned lock.
    ///
    /// Carried out so the caller reports it on stderr: ADR-0059 lets no ordinary build move a
    /// pin, and the one sanctioned exception must never happen silently.
    pub shed_vivarium: bool,
}

impl ResolvedComposition {
    /// Resolves the composition closure and effective lock without writing.
    ///
    /// # Errors
    ///
    /// Returns [`GeneratedFlakeError`] for invalid path components, unresolved artifacts,
    /// malformed declarations, an unbounded `extends`, or a lock probe failure.
    #[allow(clippy::too_many_lines)]
    pub fn resolve(
        roots: &XdgRoots,
        sandbox_id: &str,
        target: &str,
        selected_manifest: &ResolvedArtifact,
        manifest_source: &str,
        manifest: &Manifest,
    ) -> Result<Self, GeneratedFlakeError> {
        // ADR-0107 keys every generated path on the selected manifest name. This remains a
        // component backstop even though artifact resolution already enforces its public grammar.
        validate_component(sandbox_id, "manifest name")?;
        validate_component(target, "target")?;
        let image = resolve_layer(&roots.config, ArtifactKind::Image, &manifest.image)?;
        let pieces = manifest
            .pieces
            .iter()
            .map(|name| resolve_layer(&roots.config, ArtifactKind::Piece, name))
            .collect::<Result<Vec<_>, _>>()?;

        let mut inputs = BTreeMap::new();
        for artifact in std::iter::once(&image).chain(&pieces) {
            if artifact.form == ArtifactForm::Directory {
                let path = artifact
                    .path
                    .parent()
                    .ok_or_else(|| {
                        GeneratedFlakeError::plain(
                            GeneratedFlakeErrorKind::Internal,
                            Namespace::Internal,
                            "artifact-parent",
                            Locus::File(artifact.path.clone()),
                            "resolved directory artifact has no parent",
                            "the resolver returned an impossible directory form",
                        )
                    })?
                    .join("inputs.toml");
                match fs::read(&path) {
                    // Bytes first, then decoding: a file that reads but does not decode is an
                    // authored defect (`manifest.syntax`, 78), not a failure of the channel
                    // (`manifest.inputs-read`, 74/77). `read_to_string` collapses the two.
                    Ok(bytes) => {
                        let source = decode_inputs(bytes, &path)?;
                        merge_inputs(
                            &mut inputs,
                            parse_inputs(
                                &source,
                                &path,
                                &InputDeclarer {
                                    kind: artifact.kind,
                                    name: artifact.name.clone(),
                                    path: path.clone(),
                                },
                            )
                            .map_err(|error| input_failure(&error))?,
                        )
                        .map_err(|error| input_failure(&error))?;
                    }
                    Err(source) if source.kind() == std::io::ErrorKind::NotFound => {}
                    Err(source) => {
                        return Err(GeneratedFlakeError::io(
                            Namespace::Manifest,
                            "inputs-read",
                            path.clone(),
                            format!("could not read `{}`", path.display()),
                            source,
                        ));
                    }
                }
            }
        }

        let extends = manifest
            .extends
            .as_deref()
            .map(|value| resolve_extends(selected_manifest, value, manifest_source))
            .transpose()?;
        let paths = target_paths(roots, sandbox_id, target, selected_manifest)?;
        let effective_lock = paths.select_lock()?;

        Ok(Self {
            image,
            pieces,
            extends,
            inputs,
            paths,
            effective_lock,
        })
    }
}

/// The three durable paths one target owns, computed without touching the filesystem.
///
/// Separate from [`ResolvedComposition::resolve`] because `viv config` needs exactly these and
/// nothing else: it reports where the generated flake and the lock in force live whether or not
/// they exist, and it must answer that for a manifest whose image is not installed. Folding the
/// path arithmetic into composition resolution would make "where would this be written" depend on
/// every artifact the manifest names resolving first.
///
/// # Errors
///
/// Returns [`GeneratedFlakeError`] only for the impossible tree shape of a directory-form manifest
/// with no parent directory.
pub fn target_paths(
    roots: &XdgRoots,
    sandbox_id: &str,
    target: &str,
    selected_manifest: &ResolvedArtifact,
) -> Result<GeneratedFlakePaths, GeneratedFlakeError> {
    let override_lock = if selected_manifest.form == ArtifactForm::Directory {
        Some(
            selected_manifest
                .path
                .parent()
                .ok_or_else(|| {
                    GeneratedFlakeError::plain(
                        GeneratedFlakeErrorKind::Internal,
                        Namespace::Internal,
                        "manifest-parent",
                        Locus::File(selected_manifest.path.clone()),
                        "resolved directory manifest has no parent",
                        "the resolver returned an impossible directory form",
                    )
                })?
                .join(LOCK_FILE),
        )
    } else {
        None
    };
    Ok(GeneratedFlakePaths {
        directory: roots.cache.join("flakes").join(sandbox_id).join(target),
        owned_lock: roots
            .data
            .join("projects")
            .join(sandbox_id)
            .join(target)
            .join(LOCK_FILE),
        override_lock,
    })
}

impl GeneratedFlakePaths {
    /// Chooses the lock in force: a present team override, else the tool-owned pin.
    ///
    /// # Errors
    ///
    /// Returns [`GeneratedFlakeError`] when a candidate cannot be inspected.
    pub fn select_lock(&self) -> Result<EffectiveLock, GeneratedFlakeError> {
        if let Some(path) = &self.override_lock
            && probe_lock(path)?
        {
            return Ok(EffectiveLock::Override { path: path.clone() });
        }
        if probe_lock(&self.owned_lock)? {
            return Ok(EffectiveLock::OwnedExisting {
                path: self.owned_lock.clone(),
            });
        }
        Ok(EffectiveLock::OwnedMissing {
            path: self.owned_lock.clone(),
        })
    }
}

impl GeneratedFlakePlan {
    /// Builds a deterministic tree plan without writing it.
    ///
    /// # Errors
    ///
    /// Returns [`GeneratedFlakeError`] if a planned destination is not a safe relative path.
    pub fn build(
        roots: &XdgRoots,
        selected_manifest: &ResolvedArtifact,
        manifest_source: &str,
        manifest: &Manifest,
        composition: &ResolvedComposition,
        baseline: &BaselineInputs,
    ) -> Result<Self, GeneratedFlakeError> {
        let mut entries = vec![
            GeneratedEntry::RenderedFile {
                destination: PathBuf::from(FLAKE_FILE),
                bytes: render_flake(selected_manifest, composition, baseline).into_bytes(),
            },
            GeneratedEntry::RenderedFile {
                destination: PathBuf::from(OPTIONS_MODULE_FILE),
                bytes: OPTIONS_MODULE.as_bytes().to_vec(),
            },
            GeneratedEntry::RenderedFile {
                destination: PathBuf::from(REPORT_FILE),
                bytes: REPORT_MODULE.as_bytes().to_vec(),
            },
            GeneratedEntry::RenderedFile {
                destination: PathBuf::from(MANIFEST_MODULE_FILE),
                bytes: render_manifest_module(manifest).into_bytes(),
            },
            GeneratedEntry::RenderedFile {
                destination: PathBuf::from(MANIFEST_SOURCE_FILE),
                bytes: manifest_source.as_bytes().to_vec(),
            },
            GeneratedEntry::CopiedTree {
                source: roots.config.join("images"),
                destination: PathBuf::from("images"),
            },
            GeneratedEntry::CopiedTree {
                source: roots.config.join("pieces"),
                destination: PathBuf::from("pieces"),
            },
        ];
        // The embedded product tree, one entry per file, mirroring the repository layout so
        // `nix/default.nix` reaches the crate root through the same `../.` it uses in this
        // repository. Rendered on every preparation like everything above it (ADR-0058).
        for (relative, bytes) in embedded::EMBEDDED_TREE {
            entries.push(GeneratedEntry::RenderedFile {
                destination: PathBuf::from(EMBEDDED_TREE_DIRECTORY).join(relative),
                bytes: bytes.to_vec(),
            });
        }
        if let Some(extends) = &composition.extends {
            entries.push(GeneratedEntry::CopiedTree {
                source: extends.directory.clone(),
                destination: PathBuf::from("manifests").join(&extends.manifest_name),
            });
        }
        let mut migrated_lock = None;
        match &composition.effective_lock {
            // A team override is read-only to the tool by contract, so one carrying the dead
            // node is refused with the remedy named rather than rewritten in place.
            EffectiveLock::Override { path } => {
                if super::lock::carries_vivarium(&read_lock(path)?) {
                    return Err(GeneratedFlakeError::plain(
                        GeneratedFlakeErrorKind::Config,
                        Namespace::Lock,
                        "override-carries-vivarium",
                        Locus::File(path.clone()),
                        "the team override lock pins a `vivarium` input no generated flake \
                        declares any more",
                        "the installation supplies vivarium (ADR-0102), and this read-only \
                        lock predates that — whoever owns it regenerates it with a current \
                        vivarium",
                    ));
                }
                entries.push(GeneratedEntry::CopiedFile {
                    source: path.clone(),
                    destination: PathBuf::from(LOCK_FILE),
                });
            }
            EffectiveLock::OwnedExisting { path } => {
                // The one sanctioned lock rewrite (ADR-0102): shed the dead node, moving no
                // surviving pin. The staged tree gets the migrated bytes so this very
                // evaluation runs against them.
                if let Some(shed) = super::lock::shed_vivarium(&read_lock(path)?) {
                    entries.push(GeneratedEntry::RenderedFile {
                        destination: PathBuf::from(LOCK_FILE),
                        bytes: shed.clone(),
                    });
                    migrated_lock = Some(shed);
                } else {
                    entries.push(GeneratedEntry::CopiedFile {
                        source: path.clone(),
                        destination: PathBuf::from(LOCK_FILE),
                    });
                }
            }
            EffectiveLock::OwnedMissing { .. } => {}
        }
        for entry in &entries {
            validate_relative(entry.destination())?;
        }
        Ok(Self {
            directory: composition.paths.directory.clone(),
            entries,
            effective_lock: composition.effective_lock.clone(),
            migrated_lock,
        })
    }
}

/// Reads the lock in force for planning; selection already proved it exists.
fn read_lock(path: &Path) -> Result<Vec<u8>, GeneratedFlakeError> {
    fs::read(path).map_err(|source| {
        GeneratedFlakeError::io(
            Namespace::Lock,
            "read",
            path.to_path_buf(),
            format!("could not read the lock in force `{}`", path.display()),
            source,
        )
    })
}

fn resolve_layer(
    config_root: &Path,
    kind: ArtifactKind,
    name: &str,
) -> Result<ResolvedArtifact, GeneratedFlakeError> {
    resolve_artifact(config_root, kind, name).map_err(|error| match error {
        super::ResolutionError::InspectArtifact { path, source } => GeneratedFlakeError::io(
            Namespace::Manifest,
            "artifact-resolution",
            path.clone(),
            format!("could not inspect artifact candidate `{}`", path.display()),
            source,
        ),
        error => GeneratedFlakeError::plain(
            GeneratedFlakeErrorKind::Config,
            Namespace::Manifest,
            "artifact-resolution",
            Locus::File(config_root.to_path_buf()),
            error.to_string(),
            "the named composition layer could not be resolved",
        ),
    })
}

fn decode_inputs(bytes: Vec<u8>, path: &Path) -> Result<String, GeneratedFlakeError> {
    String::from_utf8(bytes).map_err(|_| {
        GeneratedFlakeError::plain(
            GeneratedFlakeErrorKind::Config,
            Namespace::Manifest,
            "syntax",
            Locus::File(path.to_path_buf()),
            format!("`{}` is not valid TOML", path.display()),
            "expected UTF-8 text",
        )
    })
}

/// Carries the whole authored diagnostic across the type boundary.
///
/// The `accepted here:` slot is conditional but load-bearing: an unknown `inputs.toml` key is a
/// compatibility message, so dropping the accepted set here would silently truncate it.
fn input_failure(error: &super::InputError) -> GeneratedFlakeError {
    GeneratedFlakeError::plain(
        GeneratedFlakeErrorKind::Config,
        Namespace::Manifest,
        error.condition(),
        error.locus(),
        error.to_string(),
        error.why(),
    )
    .with_accepted(error.accepted())
}

fn resolve_extends(
    selected_manifest: &ResolvedArtifact,
    value: &str,
    manifest_source: &str,
) -> Result<ResolvedExtends, GeneratedFlakeError> {
    let directory = selected_manifest.path.parent().ok_or_else(|| {
        invalid_extends(
            selected_manifest,
            manifest_source,
            "the selected manifest has no containing directory",
        )
    })?;
    let canonical_directory = fs::canonicalize(directory).map_err(|source| {
        extends_io_or_invalid(selected_manifest, manifest_source, directory, source)
    })?;
    let joined = directory.join(value);
    let canonical_target = fs::canonicalize(&joined).map_err(|source| {
        extends_io_or_invalid(selected_manifest, manifest_source, &joined, source)
    })?;
    let is_nix = Path::new(value)
        .extension()
        .is_some_and(|extension| extension == "nix");
    if !is_nix || !canonical_target.starts_with(&canonical_directory) || !canonical_target.is_file()
    {
        return Err(invalid_extends(
            selected_manifest,
            manifest_source,
            "expected a regular `.nix` file that remains inside the manifest directory",
        ));
    }
    Ok(ResolvedExtends {
        directory: directory.to_path_buf(),
        relative_target: PathBuf::from(value),
        manifest_name: selected_manifest.name.clone(),
    })
}

fn extends_io_or_invalid(
    selected_manifest: &ResolvedArtifact,
    manifest_source: &str,
    path: &Path,
    source: std::io::Error,
) -> GeneratedFlakeError {
    if source.kind() == std::io::ErrorKind::PermissionDenied {
        GeneratedFlakeError::io(
            Namespace::Manifest,
            "extends-inspect",
            path.to_path_buf(),
            format!("could not inspect extends target `{}`", path.display()),
            source,
        )
    } else {
        invalid_extends(
            selected_manifest,
            manifest_source,
            "the extends target does not exist",
        )
    }
}

fn invalid_extends(
    selected_manifest: &ResolvedArtifact,
    manifest_source: &str,
    why: &str,
) -> GeneratedFlakeError {
    let locus = manifest_source.find("extends").map_or_else(
        || Locus::File(selected_manifest.path.clone()),
        |offset| Locus::in_source(&selected_manifest.path, manifest_source, offset),
    );
    GeneratedFlakeError::plain(
        GeneratedFlakeErrorKind::Config,
        Namespace::Manifest,
        "invalid-value",
        locus,
        format!(
            "invalid value for `extends` in `{}`",
            selected_manifest.name
        ),
        why,
    )
}

fn probe_lock(path: &Path) -> Result<bool, GeneratedFlakeError> {
    path.try_exists().map_err(|source| {
        GeneratedFlakeError::io(
            Namespace::Lock,
            "inspect",
            path.to_path_buf(),
            format!("could not inspect lock candidate `{}`", path.display()),
            source,
        )
    })
}

fn validate_component(component: &str, label: &'static str) -> Result<(), GeneratedFlakeError> {
    let path = Path::new(component);
    if component.is_empty()
        || path.is_absolute()
        || path.components().count() != 1
        || matches!(
            path.components().next(),
            Some(Component::CurDir | Component::ParentDir)
        )
        || component.contains(['/', '\\'])
    {
        return Err(GeneratedFlakeError::plain(
            GeneratedFlakeErrorKind::Config,
            Namespace::Manifest,
            "invalid-value",
            Locus::Named(label),
            format!("invalid {label} `{component}`"),
            "expected one non-empty relative path component",
        ));
    }
    Ok(())
}

fn validate_relative(path: &Path) -> Result<(), GeneratedFlakeError> {
    if path.as_os_str().is_empty()
        || path.is_absolute()
        || path.components().any(|component| {
            matches!(
                component,
                Component::ParentDir | Component::RootDir | Component::Prefix(_)
            )
        })
    {
        return Err(GeneratedFlakeError::plain(
            GeneratedFlakeErrorKind::Internal,
            Namespace::Internal,
            "generated-path",
            Locus::Named("generated flake plan"),
            format!("unsafe generated destination `{}`", path.display()),
            "a generated destination must remain beneath its tree",
        ));
    }
    Ok(())
}

/// The `inputs` block: the two baseline inputs every generated flake carries, then whatever the
/// composed artifacts declared.
#[allow(clippy::format_push_string)]
fn render_inputs(composition: &ResolvedComposition, baseline: &BaselineInputs) -> String {
    let mut text = String::from("  inputs = {\n");
    text.push_str(&format!(
        "    nixpkgs.url = \"{}\";\n",
        nix_string(&baseline.nixpkgs)
    ));
    text.push_str(&format!(
        "    microvm.url = \"{}\";\n",
        nix_string(&baseline.microvm)
    ));
    // The `follows` line matters: without it the composed guest would be built against one
    // nixpkgs and its shares and volumes described against another, which is a mismatch that
    // surfaces as a boot failure rather than as an evaluation error.
    text.push_str("    microvm.inputs.nixpkgs.follows = \"nixpkgs\";\n");
    for (name, input) in &composition.inputs {
        text.push_str(&format!(
            "    {name} = {{ url = \"{}\";{} }};\n",
            nix_string(&input.url),
            if input.flake { "" } else { " flake = false;" }
        ));
    }
    text.push_str("  };\n");
    text
}

#[allow(clippy::format_push_string)]
fn render_flake(
    selected_manifest: &ResolvedArtifact,
    composition: &ResolvedComposition,
    baseline: &BaselineInputs,
) -> String {
    let mut text = String::from(concat!(
        "{\n",
        "  description = \"vivarium generated project flake\";\n",
    ));
    text.push_str(&render_inputs(composition, baseline));
    text.push_str("  outputs = inputs@{ nixpkgs, microvm, ... }:\n    let\n");
    text.push_str(concat!(
        "      vivariumInputs = builtins.removeAttrs inputs ",
        "[ \"self\" \"nixpkgs\" \"microvm\" ];\n",
    ));
    // The product seam, resolved once per system from the embedded tree this binary wrote
    // (ADR-0102). `guestModule` carries the shares, volumes, store overlay and guest identity
    // the launch specification reads; `mkLaunch` renders that specification from the resolved
    // config. Both come from the same expression the diagnostic image uses, so a manifest-built
    // guest and the shipped image are one guest reached two ways — and both evaluate against
    // this flake's own `nixpkgs` and `microvm`, passed in here.
    text.push_str(&format!(
        "      product = system: import ./{EMBEDDED_TREE_DIRECTORY}/nix"
    ));
    text.push_str(" { inherit nixpkgs microvm system; };\n");
    // The composed layers, each carrying the identity the provenance view names it by. This is the
    // only place the tool's layer vocabulary — image, piece, extends, manifest — reaches Nix, and
    // `vivarium-report.nix` evaluates each `module` alone against the option surface to recover
    // what that layer contributed.
    text.push_str("      layers = [\n");
    text.push_str(&format!(
        "        {}\n",
        nix_layer(
            "image",
            &composition.image.name,
            &nix_import(&composition.image)
        )
    ));
    for piece in &composition.pieces {
        text.push_str(&format!(
            "        {}\n",
            nix_layer("piece", &piece.name, &nix_import(piece))
        ));
    }
    if let Some(extends) = &composition.extends {
        text.push_str(&format!(
            "        {}\n",
            nix_layer(
                "extends",
                &extends.manifest_name,
                &format!(
                    "./manifests/{}/{}",
                    extends.manifest_name,
                    extends.relative_target.display()
                ),
            )
        ));
    }
    text.push_str(&format!(
        "        {}\n      ];\n",
        nix_layer(
            "manifest",
            &selected_manifest.name,
            &format!("./{MANIFEST_MODULE_FILE}")
        )
    ));
    // The option surface comes first so no layer can be the module that declares the option it
    // sets, then the product guest module so every composed layer outranks it, and `microvm` last
    // because it is upstream's, not a composed layer. The guest module holds the lowest priority
    // it can for everything a user may legitimately choose, so this ordering is a statement about
    // who declares what rather than about who wins.
    text.push_str(&format!(
        "      modules = system: [ ./{OPTIONS_MODULE_FILE} (product system).guestModule ]\n"
    ));
    text.push_str("        ++ map (layer: layer.module) layers\n");
    text.push_str("        ++ [ microvm.nixosModules.microvm ];\n");
    text.push_str(concat!(
        "      build = system: nixpkgs.lib.nixosSystem { inherit system;\n",
        "        specialArgs = { inherit vivariumInputs; } // (product system).guestSpecialArgs;\n",
        "        modules = modules system; };\n",
    ));
    text.push_str(
        "      launch = system: (product system).mkLaunch { inherit ((build system)) config; };\n",
    );
    text.push_str(&format!(
        "      report = system: import ./{REPORT_FILE} {{\n"
    ));
    text.push_str(concat!(
        "        inherit (nixpkgs) lib;\n",
        "        pkgs = import nixpkgs { inherit system; };\n",
        "        inherit vivariumInputs layers;\n",
    ));
    text.push_str(&format!(
        "        optionsModule = ./{OPTIONS_MODULE_FILE};\n"
    ));
    text.push_str("        inherit (build system) config;\n      };\n");
    text.push_str(concat!(
        "    in {\n",
        "      nixosConfigurations = { x86_64-linux = build \"x86_64-linux\"; ",
        "aarch64-linux = build \"aarch64-linux\"; };\n",
    ));
    text.push_str(&format!(
        "      {REPORT_ATTR} = {{ x86_64-linux = report \"x86_64-linux\"; "
    ));
    text.push_str("aarch64-linux = report \"aarch64-linux\"; };\n");
    // What `viv start` builds. The runner is the same expression the diagnostic path executes,
    // so the host-resolved token substitution has one implementation rather than a second
    // spelling of it in Rust.
    text.push_str(concat!(
        "      launchArguments = { x86_64-linux = (launch \"x86_64-linux\").launchArguments; ",
        "aarch64-linux = (launch \"aarch64-linux\").launchArguments; };\n",
        "      runner = { x86_64-linux = (launch \"x86_64-linux\").runner; ",
        "aarch64-linux = (launch \"aarch64-linux\").runner; };\n",
    ));
    text.push_str("    };\n}\n");
    text
}

/// One entry of the generated `layers` list.
fn nix_layer(kind: &str, name: &str, module: &str) -> String {
    format!(
        "{{ name = \"{}\"; kind = \"{kind}\"; module = {module}; }}",
        nix_string(name)
    )
}

fn nix_import(artifact: &ResolvedArtifact) -> String {
    match artifact.form {
        ArtifactForm::Flat => format!("./{}/{}.nix", artifact.kind.library(), artifact.name),
        ArtifactForm::Directory => {
            format!(
                "./{}/{}/default.nix",
                artifact.kind.library(),
                artifact.name
            )
        }
    }
}

/// The manifest as the personal leaf of the merge.
///
/// Every table it declares becomes a definition of the matching tool-owned option at normal
/// priority, which is the tier spec/04 gives the manifest: it outranks an image's or a piece's
/// `mkDefault` proposal and yields to a shared piece's `mkForce` floor. What the manifest does not
/// declare is not set here at all — an emitted default would be indistinguishable from an authored
/// value in the provenance view, and would make an undeclared ceiling look decided when spec/03
/// says the host resolves it at launch.
///
/// `image`, `pieces`, and `extends` are absent on purpose: they select the layers rather than
/// contribute to the merge, and the generated flake already imports what they name.
#[allow(clippy::format_push_string)]
fn render_manifest_module(manifest: &Manifest) -> String {
    let mut vivarium = String::new();
    if !manifest.env.is_empty() {
        vivarium.push_str("    env = {");
        for (name, content) in &manifest.env {
            vivarium.push_str(&format!(
                " \"{}\" = \"{}\";",
                nix_string(name),
                nix_string(content)
            ));
        }
        vivarium.push_str(" };\n");
    }
    if !manifest.mounts.is_empty() {
        vivarium.push_str("    mounts = [");
        for mount in &manifest.mounts {
            vivarium.push_str(&format!(
                " {{ source = \"{}\"; target = \"{}\"; readonly = {}; }}",
                nix_string(&mount.source),
                nix_string(&mount.target),
                mount.readonly
            ));
        }
        vivarium.push_str(" ];\n");
    }
    if !manifest.workspaces.is_empty() {
        vivarium.push_str("    workspaces = [");
        for workspace in &manifest.workspaces {
            vivarium.push_str(&format!(
                " {{ source = \"{}\"; }}",
                nix_string(&workspace.source)
            ));
        }
        vivarium.push_str(" ];\n");
    }
    if let Some(resources) = manifest.resources
        && (resources.mem_mib.is_some() || resources.vcpu.is_some())
    {
        vivarium.push_str("    resources = {");
        render_optional_u32(&mut vivarium, "mem_mib", resources.mem_mib);
        render_optional_u32(&mut vivarium, "vcpu", resources.vcpu);
        vivarium.push_str(" };\n");
    }
    if !manifest.volumes.is_empty() {
        vivarium.push_str("    volumes = [");
        for volume in &manifest.volumes {
            vivarium.push_str(&format!(
                " {{ name = \"{}\"; mount = \"{}\";",
                nix_string(&volume.name),
                nix_string(&volume.mount)
            ));
            render_optional_u32(&mut vivarium, "size_gib", volume.size_gib);
            vivarium.push_str(" }");
        }
        vivarium.push_str(" ];\n");
    }
    if let Some(volume) = &manifest.volume {
        vivarium.push_str("    volume = {");
        render_optional_u32(&mut vivarium, "size_gib", volume.size_gib);
        if !volume.persist.is_empty() {
            vivarium.push_str(" persist = [");
            for path in &volume.persist {
                vivarium.push_str(&format!(" \"{}\"", nix_string(path)));
            }
            vivarium.push_str(" ];");
        }
        vivarium.push_str(" };\n");
    }

    let mut value = String::from("{ ... }:\n{\n");
    if !vivarium.is_empty() {
        value.push_str("  vivarium = {\n");
        value.push_str(&vivarium);
        value.push_str("  };\n");
    }
    if let Some(egress) = &manifest.egress {
        value.push_str("  sandbox.egress = {");
        if let Some(mode) = egress.mode {
            value.push_str(&format!(
                " mode = \"{}\";",
                match mode {
                    super::EgressMode::Open => "open",
                    super::EgressMode::Allowlist => "allowlist",
                }
            ));
        }
        if !egress.allow.is_empty() {
            value.push_str(" allow = [");
            for allowed in &egress.allow {
                value.push_str(&format!(" \"{}\"", nix_string(allowed)));
            }
            value.push_str(" ];");
        }
        value.push_str(" };\n");
    }
    value.push_str("}\n");
    value
}

#[allow(clippy::format_push_string)]
fn render_optional_u32(output: &mut String, name: &str, value: Option<u32>) {
    if let Some(value) = value {
        output.push_str(&format!(" {name} = {value};"));
    }
}

fn nix_string(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::os::unix::fs::symlink;
    use std::path::Path;

    use std::ffi::OsString;

    use super::{
        BaselineInputs, EffectiveLock, GeneratedEntry, GeneratedFlakePlan, ResolvedComposition,
        render_manifest_module,
    };
    use crate::config::test_support::ScratchDirectory;
    use crate::config::{ArtifactForm, ArtifactKind, Manifest, ResolvedArtifact, XdgRoots};

    /// The seam AGENTS.md's pin-in-development rule runs through, in both directions.
    #[test]
    fn the_baseline_ships_branches_and_takes_a_development_pin() {
        let shipped = BaselineInputs::from_environment(&(|_: &'static str| None));
        assert_eq!(shipped, BaselineInputs::default());
        assert!(shipped.nixpkgs.starts_with("github:"));

        let pinned = BaselineInputs::from_environment(
            &(|name: &'static str| match name {
                super::BASELINE_NIXPKGS_VARIABLE => {
                    Some(OsString::from("path:/nix/store/x-source"))
                }
                // An empty override is the shape a lane that failed to compute one would set,
                // and it must fall back rather than render an empty input URL.
                super::BASELINE_MICROVM_VARIABLE => Some(OsString::from("   ")),
                _ => None,
            }),
        );
        assert_eq!(pinned.nixpkgs, "path:/nix/store/x-source");
        assert_eq!(pinned.microvm, BaselineInputs::default().microvm);
    }

    #[test]
    fn manifest_module_renders_every_workspace_source() {
        let manifest = Manifest {
            image: "base".to_owned(),
            workspaces: vec![
                crate::config::Workspace {
                    source: "${HOME}/one".to_owned(),
                },
                crate::config::Workspace {
                    source: "/two".to_owned(),
                },
            ],
            ..Manifest::default()
        };
        assert!(
            render_manifest_module(&manifest).contains(
                "workspaces = [ { source = \"\\${HOME}/one\"; } { source = \"/two\"; } ];"
            )
        );
    }

    #[test]
    fn resolves_paths_order_inputs_and_missing_lock() -> Result<(), Box<dyn std::error::Error>> {
        let scratch = fixture()?;
        fs::create_dir_all(scratch.path().join("config/images/base"))?;
        fs::write(scratch.path().join("config/images/base/default.nix"), "{}")?;
        fs::write(
            scratch.path().join("config/images/base/inputs.toml"),
            "[inputs.zed]\nurl = 'path:z'\nflake = false",
        )?;
        fs::create_dir_all(scratch.path().join("config/pieces/one"))?;
        fs::write(scratch.path().join("config/pieces/one/default.nix"), "{}")?;
        fs::write(
            scratch.path().join("config/pieces/one/inputs.toml"),
            "[inputs.alpha]\nurl = 'github:a/b'",
        )?;
        let roots = roots(scratch.path());
        let selected = selected(scratch.path(), ArtifactForm::Flat);
        fs::create_dir_all(selected.path.parent().unwrap_or_else(|| Path::new(".")))?;
        fs::write(&selected.path, "image = 'base'")?;
        let manifest = Manifest {
            image: "base".to_owned(),
            pieces: vec!["one".to_owned(), "one".to_owned()],
            ..Manifest::default()
        };
        let composition = ResolvedComposition::resolve(
            &roots,
            "project",
            "default",
            &selected,
            "image = 'base'",
            &manifest,
        )?;
        assert_eq!(composition.pieces.len(), 2);
        assert_eq!(
            composition.inputs.keys().collect::<Vec<_>>(),
            vec!["alpha", "zed"]
        );
        assert_eq!(
            composition.paths.directory,
            scratch.path().join("cache/flakes/project/default")
        );
        assert!(matches!(
            composition.effective_lock,
            EffectiveLock::OwnedMissing { .. }
        ));
        Ok(())
    }

    #[test]
    fn plan_is_semantic_deterministic_and_excludes_manifest_library()
    -> Result<(), Box<dyn std::error::Error>> {
        let scratch = fixture()?;
        fs::create_dir_all(scratch.path().join("config/images"))?;
        fs::create_dir_all(scratch.path().join("config/pieces"))?;
        fs::write(scratch.path().join("config/images/base.nix"), "{}")?;
        let selected = selected(scratch.path(), ArtifactForm::Flat);
        fs::create_dir_all(selected.path.parent().unwrap_or_else(|| Path::new(".")))?;
        fs::write(&selected.path, "image = 'base'")?;
        let roots = roots(scratch.path());
        let manifest = Manifest {
            image: "base".to_owned(),
            env: std::iter::once(("TOKEN".to_owned(), "quote\" slash\\ ${HOME}\n".to_owned()))
                .collect(),
            ..Manifest::default()
        };
        let composition = ResolvedComposition::resolve(
            &roots,
            "project",
            "default",
            &selected,
            "image = 'base'",
            &manifest,
        )?;
        let first = GeneratedFlakePlan::build(
            &roots,
            &selected,
            "image = 'base'",
            &manifest,
            &composition,
            &BaselineInputs::default(),
        )?;
        let second = GeneratedFlakePlan::build(
            &roots,
            &selected,
            "image = 'base'",
            &manifest,
            &composition,
            &BaselineInputs::default(),
        )?;
        assert_eq!(first, second);
        assert!(first.entries.iter().any(|entry| matches!(
            entry,
            GeneratedEntry::CopiedTree { destination, .. } if destination == Path::new("images")
        )));
        assert!(!first.entries.iter().any(|entry| {
            entry.destination() == Path::new("manifests")
                || entry.destination().starts_with("manifests")
        }));
        let leaf = first.entries.iter().find_map(|entry| match entry {
            GeneratedEntry::RenderedFile { destination, bytes }
                if destination == Path::new("manifest-leaf.nix") =>
            {
                Some(bytes)
            }
            _ => None,
        });
        let text = String::from_utf8(leaf.cloned().unwrap_or_default())?;
        assert!(text.contains("\\\""));
        assert!(text.contains("\\${HOME}"));
        Ok(())
    }

    /// Item 5 of slice 015: a retained owned lock sheds its dead `vivarium` node into both the
    /// staged tree and the plan's migration copy, and a clean lock is staged byte-for-byte.
    #[test]
    fn a_retained_lock_is_migrated_and_a_clean_one_is_left_alone()
    -> Result<(), Box<dyn std::error::Error>> {
        let scratch = fixture()?;
        fs::create_dir_all(scratch.path().join("config/images"))?;
        fs::create_dir_all(scratch.path().join("config/pieces"))?;
        fs::write(scratch.path().join("config/images/base.nix"), "{}")?;
        let selected = selected(scratch.path(), ArtifactForm::Flat);
        fs::create_dir_all(selected.path.parent().unwrap_or_else(|| Path::new(".")))?;
        fs::write(&selected.path, "image = 'base'")?;
        let roots = roots(scratch.path());
        let manifest = Manifest {
            image: "base".to_owned(),
            ..Manifest::default()
        };
        let owned = scratch
            .path()
            .join("data/projects/project/default/flake.lock");
        fs::create_dir_all(owned.parent().unwrap_or_else(|| Path::new(".")))?;
        fs::write(
            &owned,
            concat!(
                r#"{"nodes":{"nixpkgs":{"locked":{"narHash":"n"}},"#,
                r#""root":{"inputs":{"nixpkgs":"nixpkgs","vivarium":"vivarium"}},"#,
                r#""vivarium":{"locked":{"narHash":"v"}}},"root":"root","version":7}"#
            ),
        )?;
        let plan = || -> Result<GeneratedFlakePlan, Box<dyn std::error::Error>> {
            let composition = ResolvedComposition::resolve(
                &roots,
                "project",
                "default",
                &selected,
                "image = 'base'",
                &manifest,
            )?;
            Ok(GeneratedFlakePlan::build(
                &roots,
                &selected,
                "image = 'base'",
                &manifest,
                &composition,
                &BaselineInputs::default(),
            )?)
        };

        let migrated = plan()?;
        let staged = migrated
            .entries
            .iter()
            .find_map(|entry| match entry {
                GeneratedEntry::RenderedFile { destination, bytes }
                    if destination == Path::new("flake.lock") =>
                {
                    Some(bytes.clone())
                }
                _ => None,
            })
            .ok_or("a retained lock is staged as migrated bytes, not copied")?;
        assert_eq!(migrated.migrated_lock.as_deref(), Some(staged.as_slice()));
        let text = String::from_utf8(staged)?;
        assert!(!text.contains("vivarium"));
        assert!(text.contains("nixpkgs"));

        // A lock with nothing to shed keeps the copied-bytes seam and no migration copy.
        fs::write(
            &owned,
            concat!(
                r#"{"nodes":{"nixpkgs":{"locked":{"narHash":"n"}},"#,
                r#""root":{"inputs":{"nixpkgs":"nixpkgs"}}},"root":"root","version":7}"#
            ),
        )?;
        let clean = plan()?;
        assert!(clean.migrated_lock.is_none());
        assert!(clean.entries.iter().any(|entry| matches!(
            entry,
            GeneratedEntry::CopiedFile { destination, .. } if destination == Path::new("flake.lock")
        )));
        Ok(())
    }

    /// ADR-0102: the generated flake declares no `vivarium` input, and the binary writes the
    /// product tree it carries instead.
    #[test]
    fn the_binary_supplies_the_product_tree() -> Result<(), Box<dyn std::error::Error>> {
        let scratch = fixture()?;
        fs::create_dir_all(scratch.path().join("config/images"))?;
        fs::create_dir_all(scratch.path().join("config/pieces"))?;
        fs::write(scratch.path().join("config/images/base.nix"), "{}")?;
        let selected = selected(scratch.path(), ArtifactForm::Flat);
        fs::create_dir_all(selected.path.parent().unwrap_or_else(|| Path::new(".")))?;
        fs::write(&selected.path, "image = 'base'")?;
        let roots = roots(scratch.path());
        let manifest = Manifest {
            image: "base".to_owned(),
            ..Manifest::default()
        };
        let composition = ResolvedComposition::resolve(
            &roots,
            "project",
            "default",
            &selected,
            "image = 'base'",
            &manifest,
        )?;
        let plan = GeneratedFlakePlan::build(
            &roots,
            &selected,
            "image = 'base'",
            &manifest,
            &composition,
            &BaselineInputs::default(),
        )?;

        let flake = plan
            .entries
            .iter()
            .find_map(|entry| match entry {
                GeneratedEntry::RenderedFile { destination, bytes }
                    if destination == Path::new("flake.nix") =>
                {
                    Some(String::from_utf8(bytes.clone()))
                }
                _ => None,
            })
            .ok_or("the plan renders a flake")??;
        assert!(!flake.contains("vivarium.url"));
        assert!(!flake.contains("vivarium.inputs"));
        assert!(flake.contains("import ./vivarium/nix { inherit nixpkgs microvm system; }"));

        let rendered: Vec<&Path> = plan
            .entries
            .iter()
            .map(GeneratedEntry::destination)
            .collect();
        // The tree the guest-agent derivation builds from: the product Nix files and the crate
        // source, mirroring the repository layout.
        for expected in [
            "vivarium/nix/default.nix",
            "vivarium/nix/guest.nix",
            "vivarium/nix/launch-arguments.nix",
            "vivarium/nix/runner.nix",
            "vivarium/nix/runner.sh",
            "vivarium/Cargo.toml",
            "vivarium/Cargo.lock",
            "vivarium/build.rs",
            "vivarium/src/main.rs",
            "vivarium/crates/vivarium-guest-agent/Cargo.toml",
        ] {
            assert!(
                rendered.contains(&Path::new(expected)),
                "missing embedded entry {expected}"
            );
        }
        // The publication flake and the product lock stay out: the embedded tree is imported as
        // a directory, and the flake file is the sole sanctioned edge to `tests/nix`.
        for excluded in ["vivarium/nix/flake.nix", "vivarium/nix/flake.lock"] {
            assert!(
                !rendered.contains(&Path::new(excluded)),
                "excluded entry {excluded} was embedded"
            );
        }
        Ok(())
    }

    #[test]
    fn extends_is_bounded_and_override_wins() -> Result<(), Box<dyn std::error::Error>> {
        let scratch = fixture()?;
        fs::create_dir_all(scratch.path().join("config/images"))?;
        fs::create_dir_all(scratch.path().join("config/pieces"))?;
        fs::write(scratch.path().join("config/images/base.nix"), "{}")?;
        let selected = selected(scratch.path(), ArtifactForm::Directory);
        fs::create_dir_all(selected.path.parent().unwrap_or_else(|| Path::new(".")))?;
        fs::write(&selected.path, "image = 'base'\nextends = 'extra.nix'")?;
        fs::write(selected.path.with_file_name("extra.nix"), "{}")?;
        fs::write(selected.path.with_file_name("flake.lock"), "override")?;
        let roots = roots(scratch.path());
        fs::create_dir_all(scratch.path().join("data/projects/project/default"))?;
        fs::write(
            scratch
                .path()
                .join("data/projects/project/default/flake.lock"),
            "owned",
        )?;
        let manifest = Manifest {
            image: "base".to_owned(),
            extends: Some("extra.nix".to_owned()),
            ..Manifest::default()
        };
        let composition = ResolvedComposition::resolve(
            &roots,
            "project",
            "default",
            &selected,
            "image = 'base'\nextends = 'extra.nix'",
            &manifest,
        )?;
        assert!(matches!(
            composition.effective_lock,
            EffectiveLock::Override { .. }
        ));

        // A read-only team pin carrying the dead `vivarium` node is refused, never rewritten
        // (ADR-0102, ADR-0059): the plan is where the refusal lands, before anything is staged.
        fs::write(
            selected.path.with_file_name("flake.lock"),
            concat!(
                r#"{"nodes":{"root":{"inputs":{"vivarium":"vivarium"}},"#,
                r#""vivarium":{"locked":{}}},"root":"root","version":7}"#
            ),
        )?;
        let Err(refused) = GeneratedFlakePlan::build(
            &roots,
            &selected,
            "image = 'base'\nextends = 'extra.nix'",
            &manifest,
            &composition,
            &BaselineInputs::default(),
        ) else {
            return Err("an override lock pinning `vivarium` must refuse".into());
        };
        assert!(format!("{refused:?}").contains("override-carries-vivarium"));
        Ok(())
    }

    /// An `inputs.toml` that reads but does not decode or parse is the author's defect, and its
    /// unknown-key form is a compatibility message that must survive the type boundary whole.
    #[test]
    fn undecodable_inputs_are_authored_defects_and_unknown_keys_keep_accepted()
    -> Result<(), Box<dyn std::error::Error>> {
        let scratch = fixture()?;
        fs::create_dir_all(scratch.path().join("config/pieces"))?;
        fs::create_dir_all(scratch.path().join("config/images/base"))?;
        let inputs = scratch.path().join("config/images/base/inputs.toml");
        fs::write(scratch.path().join("config/images/base/default.nix"), "{}")?;
        let selected = selected(scratch.path(), ArtifactForm::Flat);
        fs::create_dir_all(selected.path.parent().unwrap_or_else(|| Path::new(".")))?;
        fs::write(&selected.path, "image = 'base'")?;
        let roots = roots(scratch.path());
        let manifest = Manifest {
            image: "base".to_owned(),
            ..Manifest::default()
        };

        fs::write(&inputs, [0xff, 0xfe, 0x00])?;
        let undecodable = ResolvedComposition::resolve(
            &roots,
            "project",
            "default",
            &selected,
            "image = 'base'",
            &manifest,
        )
        .err()
        .ok_or("undecodable inputs unexpectedly resolved")?;
        assert_eq!(undecodable.exit_code(), crate::exit::ExitKind::Config);
        assert!(
            undecodable
                .diagnostic()
                .to_string()
                .contains("manifest.syntax")
        );

        fs::write(&inputs, "[inputs.ok]\nurl = 'x'\nrevision = 'y'\n")?;
        let unknown = ResolvedComposition::resolve(
            &roots,
            "project",
            "default",
            &selected,
            "image = 'base'",
            &manifest,
        )
        .err()
        .ok_or("unknown inputs key unexpectedly resolved")?;
        let rendered = unknown.diagnostic().to_string();
        assert!(rendered.contains("manifest.unknown-key"));
        assert!(rendered.contains("accepted here: url, flake"));
        Ok(())
    }

    #[test]
    fn extends_rejects_missing_and_canonical_escape_targets()
    -> Result<(), Box<dyn std::error::Error>> {
        let scratch = fixture()?;
        fs::create_dir_all(scratch.path().join("config/images"))?;
        fs::create_dir_all(scratch.path().join("config/pieces"))?;
        fs::write(scratch.path().join("config/images/base.nix"), "{}")?;
        let selected = selected(scratch.path(), ArtifactForm::Directory);
        let manifest_directory = selected.path.parent().unwrap_or_else(|| Path::new("."));
        fs::create_dir_all(manifest_directory)?;
        fs::write(&selected.path, "image = 'base'\nextends = 'extra.nix'")?;
        let roots = roots(scratch.path());
        let manifest = Manifest {
            image: "base".to_owned(),
            extends: Some("extra.nix".to_owned()),
            ..Manifest::default()
        };

        let missing = ResolvedComposition::resolve(
            &roots,
            "project",
            "default",
            &selected,
            "image = 'base'\nextends = 'extra.nix'",
            &manifest,
        )
        .err()
        .ok_or("missing extends target unexpectedly resolved")?;
        assert_eq!(missing.exit_code(), crate::exit::ExitKind::Config);

        let outside = scratch.path().join("config/manifests/outside.nix");
        fs::write(&outside, "{}")?;
        symlink("../outside.nix", manifest_directory.join("extra.nix"))?;
        let escaping = ResolvedComposition::resolve(
            &roots,
            "project",
            "default",
            &selected,
            "image = 'base'\nextends = 'extra.nix'",
            &manifest,
        )
        .err()
        .ok_or("escaping extends target unexpectedly resolved")?;
        assert_eq!(escaping.exit_code(), crate::exit::ExitKind::Config);
        assert!(
            escaping
                .diagnostic()
                .to_string()
                .contains("manifest.invalid-value")
        );
        Ok(())
    }

    fn fixture() -> Result<ScratchDirectory, Box<dyn std::error::Error>> {
        let scratch = ScratchDirectory::new()?;
        fs::create_dir_all(scratch.path().join("config"))?;
        Ok(scratch)
    }

    fn roots(base: &Path) -> XdgRoots {
        XdgRoots {
            config: base.join("config"),
            data: base.join("data"),
            state: base.join("state"),
            cache: base.join("cache"),
        }
    }

    fn selected(base: &Path, form: ArtifactForm) -> ResolvedArtifact {
        let path = match form {
            ArtifactForm::Flat => base.join("config/manifests/demo.toml"),
            ArtifactForm::Directory => base.join("config/manifests/demo/default.toml"),
        };
        ResolvedArtifact {
            kind: ArtifactKind::Manifest,
            name: "demo".to_owned(),
            form,
            path,
        }
    }
}
