[package]
name = "vivarium-guest-agent"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
pty-process = { version = "0.5.3", features = ["async"] }
rustix = { version = "1.1.4", features = ["process"] }
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "process",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-util = { version = "0.7.18", features = ["rt"] }
tokio-vsock = "0.7.2"
vivarium = { path = "../..", default-features = false }

[lints]
workspace = true
